FlatFilers/flatfile-core-libraries

.changeset/giant-bottles-give.md, packages/javascript/package.json, packages/listener/package.json, packages/react/package.json, packages/v2-shims/package.json
Switches from using the browser overrides to using nested entry points that include browser entries.
=> feat: nested entry points

.changeset/tough-ants-fry.md, packages/react/src/hooks/useCreateListener.ts
Fixes an issue, where updating the accessToken from creating a space doesn't actually refresh the Listener.
=> feat: update deps of useCreateListener to remount the listener when updating the accesstoken

.changeset/silver-rivers-collect.md, packages/cli/src/shared/localized/en-us.ts, packages/cli/src/x/actions/develop.action.ts
A prompt does not appear to confirm development unless there are deployed agents
Develop on an env without an agent
=> Fix develop confirm prompt firing when there are no agents

.changeset/healthy-queens-march.md, packages/javascript/FlatfileJavascript.ts, packages/react/src/utils/initializeSpace.tsx
- fix: only include params if set (especially `namespace`, `translationPath`, and `languageOverride`)
- chore: changeset
=> fix: Only Include Params If Defined

.changeset/long-buses-allow.md, packages/embedded-utils/src/types/Space.ts, packages/javascript/FlatfileJavascript.ts, packages/javascript/src/services/document.ts, packages/javascript/src/services/workbook.ts, packages/javascript/src/types/UpdateSpaceInfo.ts, packages/javascript/src/types/index.ts, packages/react/src/utils/_tests_/initializeSpace.spec.ts, packages/react/src/utils/addSpaceInfo.ts, packages/react/src/utils/getSpace.tsx, packages/react/src/utils/initializeSpace.tsx, packages/vue/src/components/SpaceC.vue, packages/vue/src/utils/addSpaceInfo.ts, packages/vue/src/utils/getSpace.ts, packages/vue/src/utils/initializeSpace.ts, packages/vue/src/utils/useInitializeSpace.ts
This makes removes environmentId as a required prop since it can be inferred from the credentials and is no longer required in the API endpoints used in the SDKs
This removes environmentId as a required prop, but does pass it along in case we get credentials in the future that has access to multiple environments.
=> Feat: Make EnvironmentID Optional

.changeset/fluffy-peas-relate.md, packages/javascript/FlatfileJavascript.ts
‼️ Depends on https://github.com/FlatFilers/Platform/pull/6953
Description:
This PR integrates the new `/init` endpoint into the Flatfile Javascript SDK. This new endpoint receives the _entire_ configuration necessary to create a space/workbook/document all in a single REST request, with the intention of optimizing embed load times. Additionally, the `response` from the new endpoint is inclusive of all data properties needed to render the initial `spaces-ui` landing page. Therefore, the full `initialResources` response is passed into `spaces-ui` via `postMessage` to ensure the UI can take the appropriate action to hydrate the UI when it loads
- Run the `vanillaJS` app locally
- Pass a space, workbook, and document config into the `initializeFlatfile` function calls for both the `preload` …
=> feat: update JS SDK to leverage new BFF init endpoint

.changeset/angry-jobs-shake.md, .changeset/heavy-mayflies-collect.md, .changeset/mean-years-heal.md, .changeset/swift-carrots-invent.md, apps/react/app/App.tsx, apps/react/app/page.tsx, apps/react/app/sheet/App.tsx, apps/react/next.config.js, packages/listener/src/event-drivers/_EventDriver.ts, packages/listener/src/flatfile.listener.ts, packages/react/src/components/Document.tsx, packages/react/src/components/EmbeddedIFrameWrapper.tsx, packages/react/src/components/FlatfileContext.tsx, packages/react/src/components/FlatfileProvider.tsx, packages/react/src/components/Sheet.tsx, packages/react/src/components/Space.tsx, packages/react/src/components/Workbook.tsx, packages/react/src/components/_tests_/Document.spec.tsx, packages/react/src/components/_tests_/FlatfileProvider.spec.tsx, packages/react/src/components/_tests_/Sheet.spec.tsx, packages/react/src/components/_tests_/Space.spec.tsx, packages/react/src/components/_tests_/Workbook.spec.tsx, packages/react/src/components/embeddedStyles.tsx, packages/react/src/components/style.scss, packages/react/src/hooks/useFlatfile.ts, packages/react/src/types/iFrameProps.ts, packages/react/src/types/index.ts, packages/react/src/utils/convertDatesToISO.ts
You can now add defaultPage={true} to any Document or Sheet in the FlatfileProvider and it will launch the Space going to that Resource. 
Here's the syntax:
```tsx
<Space>
<Document defaultPage={true} config={document} />
OR
<Sheet defaultPage={true} config={sheetConfig} />
</Space>
```
- `resetOnClose: true` to `FlatfileProvider` will reset the Space on Close for the the Close X box and the `closePortal()` helper function.
```tsx
<FlatfileProvider
publishableKey={PUBLISHABLE_KEY}
config={{
resetOnClose: false
}}
>
<App />
</FlatfileProvider>
```
- You can also override that setting by passing `closePortal({ reset: true })` and it will also reset the Portal 
```tsx
const App = () => {
const { open, openPortal, closePortal } = useFlatfile()
const toggleOpen = () => {
open ? closePortal({ …
```
=> feat: Adds `DefaultPage` To React and Resetting the Portal on Close

.changeset/fair-zebras-smash.md, .changeset/hungry-ravens-buy.md, apps/react/app/App.tsx, packages/react/src/components/EmbeddedIFrameWrapper.tsx, packages/react/src/components/FlatfileContext.tsx, packages/react/src/components/FlatfileProvider.tsx, packages/react/src/components/_tests_/FlatfileProvider.spec.tsx, packages/react/src/hooks/useFlatfile.ts
This allows for users to open the portal instance on page load:
```ts
useEffect(() => {
openPortal();
}, []);
```
=> feat: check if context is ready before triggerin openPortal()

.changeset/dirty-masks-camp.md, apps/react/app/App.tsx, apps/react/app/config.ts, apps/react/next.config.js, apps/react/utils/sheet.ts, packages/react/src/components/EmbeddedIFrameWrapper.tsx, packages/react/src/components/FlatfileContext.tsx, packages/react/src/components/FlatfileProvider.tsx, packages/react/src/components/_tests_/FlatfileProvider.spec.tsx, packages/react/src/components/style.scss, packages/react/src/hooks/useFlatfile.ts, packages/react/src/utils/useIsIFrameLoaded.ts
This has been test in `Next.js` and `create-react-app` (which have 2 different behaviors).
For example:
```
useEffect(() => {
openPortal()
}, [])
```
=> fix: Try posting to iFrame if the iframe isn not ready before the context is

.changeset/spotty-cats-brush.md, package-lock.json, packages/cli/package.json, packages/cli/src/x/actions/deploy.action.ts
This fixes an issue with the cli was not picking up all the events in an array if an array of topics was passed to the listener.
Also updates the @flatfile/api package.
Check when both the listener topics are arrays and when its a string.
eg string:
```
export default (listener) => {
listener.on('commit:created', (event) => console.log(event))
}
```
eg array:
```
export default (listener) => {
listener.on(['commit:created', 'layer:created'], (event) => console.log(event))
}
```
Closes https://github.com/FlatFilers/flatfile-core-libraries/issues/127
=> Enable cli to infer array of events

.changeset/tricky-socks-judge.md, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .prettierrc, apps/vanilla/index.html, apps/vanilla/main.js, apps/vanilla/styles.css, package-lock.json, package.json, packages/javascript/FlatfileJavascript.ts
- Ensures that the event for closing the space is only fired once
- Ensures that when closing a space, opening a new space, and closing the new space, that the close event listener from the first space is unregistered, to avoid duplicate events being handled
- Ensures that the close confirmation modal element is cleanly removed after the space is closed
Test both preloaded and on-demand spaces in `apps/vanilla`, you should see the following close event payload in the browser console after clicking "Continue" after submitting your data:
=> Close Space event payload, properly remove confirmation modal element on close, and ensure duplicate events are not fired when opening multiple Spaces

.changeset/honest-donkeys-cry.md, packages/embedded-utils/src/utils/handlePostMessage.ts, packages/javascript/FlatfileJavascript.ts
Consolidates close event handling into a single `addEventListener` call
Test `apps/vanilla` both preloaded and on-demand, and ensure that the close event is logged in the console after submitting and acknowledging submit success by pressing "Continue"
=> clean up close event handling

.changeset/bright-sloths-rule.md, apps/vue/src/App.vue, apps/vue/src/config.ts, packages/vue/rollup.config.js, packages/vue/src/components/initializeFlatfile.ts, packages/vue/src/utils/addSpaceInfo.ts, packages/vue/src/utils/initializeSpace.ts
Allows setting the defaultPage on a `Document`, `Workbook` or `Sheet` when creating a New Space in the Portal.
An example of setting the `defaultPage` on a Document:
```
const spaceProps = ref({
name: 'Trste!',
publishableKey,
workbook,
listener,
document: {
title: 'Instructions',
body:
'# Supported file types\n' +
'---\n' +
'Please only import CSV and Excel files',
defaultPage: true,
},
})
```
An example of setting the `defaultPage` on a Sheet in a Workbook:
```
export const workbook = {
name: 'All Data',
labels: ['pinned'],
sheets: [
{
name: 'Contacts',
slug: 'contacts',
allowAdditionalFields: true,
fields: [...],
},
{
name: 'Contacts 2',
slug: 'contacts2',
allowAdditionalFields: true,
defaultPage: [...],
},
]
}
```
=> feat: Fix `defaultPage` in Vue

.changeset/young-ants-whisper.md, apps/react/app/page.module.css, packages/react/src/components/EmbeddedIFrameWrapper.tsx, packages/react/src/components/embeddedStyles.tsx, packages/react/src/components/style.scss
Prevents Flatfile modal from blocking scroll on some browsers when closed
In `apps/react`, test that the closed modal no longer covers the entire page, can use inspect element to confirm. Does not affect smooth opening fade in transition.
When open:
When closed:
Fixes https://github.com/FlatFilers/support-triage/issues/1417
=> fix(react): prevent closed Flatfile modal from covering page

.changeset/thirty-boxes-approve.md, apps/react/app/App.tsx, packages/react/rollup.config.js, packages/react/src/components/ConfirmCloseModal.tsx, packages/react/src/components/Spinner.tsx, packages/react/src/index.ts, packages/react/src/scss.d.ts, packages/react/src/utils/styleInject.ts, packages/react/tsconfig.json
Now required to attach stylesheet explicitly with attachStyleSheet() from @flatfile/react, with optional nonce property to support Content Security Policies that apply to style tags.
In `apps/react`, verify that the attached Flatfile stylesheet has the expected `nonce` attribute:
Resolves https://github.com/FlatFilers/support-triage/issues/1021
=> feat(react): attachStyleSheet must be done manually now

.github/workflows/cl-create.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, cl-config.yml, package-lock.json, package.json
NA
Once the action is merged creating a new package tag via release should result in a new pr to the guides repo.
Here's [an example ](https://github.com/FlatFilers/Guides/pull/1176)installed on a dummy package.
Note: Other actions received an added step to auth them with the changelog package.
=> Install change log for automated updates

.changeset/ninety-shoes-travel.md, packages/javascript/rollup.config.js
Fixes issue where the bundle was not properly built for UMD use when transpiling **typescript** -> **javascript** with `@rollup/plugin-sucrase`
=> fix: umd build issue

packages/embedded-utils/src/utils/handlePostMessage.ts
Last PR's changelog covers this #142 
Requires https://github.com/FlatFilers/Platform/pull/7809
For now keys are only set in Chinese (zh). This can be tested by choosing the override language in the dropdown:
If you wait long enough before clicking close, so that the postMessage containing translation data may be received by `@flatfile/javascript`:
If you close the modal right away before it finished loading, you get the default fallback english strings (or custom overrides provided, which override any translation files):
=> feat(javascript): add i18n to wrapper

.changeset/unlucky-snails-clean.md, packages/react/src/components/style.scss
`@flatfile/react`: Replaced CSS text color variable name to be consistent with other variable names, --ff-color-text is now --ff-text-color
Set `--ff-text-color` variable in CSS.
=> fix(react): update CSS text color variable name

.github/workflows/release.yml
Uses GH_TOKEN to overcome the inherent limitations of [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
Attempt a release
=> fix(actions): use GH_TOKEN instead of GITHUB_TOKEN for release action

.changeset/fast-peaches-return.md, packages/react/src/hooks/useEvent.ts, packages/react/src/hooks/useListener.ts, packages/react/src/hooks/usePlugin.ts
Fixes a bug that doesn't re-attach linked listener code when changes to the Browser Driver happen. This happens when the `accessToken` is set after Space creation, so can cause a state where the listener is not attached to the client instance initially if it is not set inline. 
```tsx
'use client'
import { workbook } from '@/utils/workbook'
import FlatfileListener from '@flatfile/listener'
import { recordHook } from '@flatfile/plugin-record-hook'
import {
FlatfileProvider,
Sheet,
Space,
useFlatfile,
useListener
} from '@flatfile/react'
import { useMemo, useState } from 'react'
import styles from './page.module.css'
export const AppWrapper = ({
PUBLISHABLE_KEY,
}: {
PUBLISHABLE_KEY: string
}) => {
const [listenerVersion, setListenerVersion] = useState<number>(0)
const contactsRecordHooks = …
```
=> fix: Re-Attach Listener After AccessToken Updates

.changeset/real-years-watch.md, apps/react/app/App.tsx, apps/react/app/OldApp.tsx, apps/react/app/globals.css, apps/react/app/page.tsx, packages/react/src/components/FlatfileContext.tsx, packages/react/src/components/FlatfileProvider.tsx, packages/react/src/components/_tests_/FlatfileProvider.spec.tsx, packages/react/src/components/embeddedStyles.tsx, packages/react/src/components/style.scss, packages/react/src/hooks/legacy/usePortal.tsx, packages/react/src/hooks/legacy/useSpace.tsx, packages/react/src/hooks/legacy/useSpaceTrigger.tsx, packages/react/src/hooks/useFlatfile.ts, packages/react/src/utils/attachStyleSheet.ts
To test onClose, check for the message "Flatfile Portal closed" in the logs after closing the portal manually with the (x) button in apps/react
To test deprecated usePortal and useSpace flows in apps/react OldApp, replace App with OldApp in apps/react (tested locally w/Alex Rock already)
=> React: onClose handler on useFlatfile and attach style sheet on usePortal and useSpace

.changeset/young-peaches-occur.md, apps/vanilla/cdn.html, packages/embedded-utils/src/types/Space.ts, packages/javascript/src/listener.ts, packages/javascript/src/startFlatfile.ts
Fixes https://github.com/FlatFilers/support-triage/issues/1505
JavaScript: allow specifying submit complete options:
```
submitSettings: {
complete: {
acknowledge: true, // if false the message is a toast, if true it's a dialog box
message: 'Submitting data is now complete!',
},
},
```
Additionally, setting `submitSettings.complete.acknowledge = true` will allow Portal to be auto closed after the user presses "Continue" with the following settings set (and no `listener`):
```
closeSpace: {
operation: 'simpleSubmitAction',
onClose: () => {
console.log('Portal is now closed!')
},
},
```
Test with `apps/vanilla`
=> feat(JavaScript): allow passing submit complete options

.changeset/afraid-jars-reply.md, packages/javascript/src/createIframe.ts
JavaScript: Portal style sheet is now only attached once, instead of every time the Portal is opened.
Fixes https://github.com/FlatFilers/support-triage/issues/1508
In `apps/vanilla` close and re-open the Portal many times. Check that there is only one Flatfile stylesheet added to `<head>`.
=> fix(javascript): attach style sheet only once

.changeset/soft-mangos-bathe.md, apps/react/app/App.tsx, apps/react/app/page.tsx, packages/react/src/components/FlatfileContext.tsx, packages/react/src/components/FlatfileProvider.tsx, packages/react/src/components/_tests_/FlatfileProvider.spec.tsx, packages/react/src/hooks/useFlatfile.ts
Fixes https://github.com/FlatFilers/support-triage/issues/1513
Fix bug causing "Maximum update depth exceeded" React error when multiple Portals are used within the same FlatfileProvider (this is not supported).
`apps/react` now has two separate `<FlatfileProvider>` and `useFlatfile()` instances, this can be tested to see that the bug does not occur and the Portals behave independently.
The main issue was two `useFlatfile` hooks sharing the same FlatfileContext, however that is still not possible even after this PR, since the Context can only hold one state.
Replacing the `onClose` state with a mutable ref prevents the "Maximum update depth exceeded" error.
=> fix(react): use a ref for onClose

.changeset/witty-cobras-sniff.md, apps/react/app/sheet/App.tsx, apps/react/app/workbook/App.tsx, packages/embedded-utils/src/types/Space.ts, packages/react/src/utils/constants.ts
Fixes https://github.com/FlatFilers/support-triage/issues/1608
Added option submitSettings startingJobMessage to configure the initial message displayed in the job progress modal.
Test apps/react with various `submitSettings={{ startingJobMessage }}` props.
=> feat(react): allow specifying submitSettings.startingJobMessage

.changeset/mean-buckets-relate.md, package-lock.json, packages/hooks/src/classes/FlatfileRecord.spec.ts, packages/hooks/src/classes/FlatfileRecord.ts
Added public `getErrors` method on the FlatfileRecord class.
Add an error to a field. Then call `getErrors` to see the error returned.
=> Feat: Add getErrors public method on FlatfileRecord class

package-lock.json, packages/angular/angular-sdk/package.json, packages/angular/angular-sdk/src/lib/sdk/space.service.ts
Parameters were missing from the props passed to initNewSpace() for the Angular SDK.
Confirm that custom name and languageOverride settings are correctly set on the space.
=> Add some missing parameters to space creation

packages/react/src/components/CloseButton.tsx, packages/react/src/components/style.scss
Updates css of close button to prevent overlap
=> Update css for close button to prevent overlap

.changeset/twelve-planes-relate.md, packages/javascript/src/createIframe.ts, packages/react/src/components/EmbeddedIFrameWrapper.tsx, packages/react/src/components/legacy/InitSpace.tsx, packages/react/src/components/legacy/LegacySpace.tsx, packages/vue/src/components/SpaceC.vue
this (hopefully) fixes an issue encountered by customers using an embedded space in a setup where the parent html page is being served with a `Permissions-Policy: sync-xhr()` policy, which causes the browser to block synchronous http requests from the iframe. This matters because the embedded spaces-ui now needs to make a synchronous request to `https://cdn.flatfile.com/config/spaces-ui/platform.flatfile.com.config.js` in order to fetch the frontend config, which has to happen synchronous so the config vars are available prior to loading the react app. 
the fix will also require the customer to set their `Permissions-Policy: sync-xhr('self' '*.flatfile.com')` to allow the request. The iframe.allow attribute has to agree with the server policy.
=> allow sync-xhr requests to self and *.flatfile.com domains in the iframe

packages/react/src/components/FlatfileProvider.tsx
Uses `debugLogger` so it's still there with `debug: true`
=> Fix debug statement

.changeset/spicy-moons-provide.md, packages/react/src/components/FlatfileProvider.tsx, packages/react/src/utils/getSpace.tsx
The `spaceUrl` setting was not being respected when using existing spaces, this makes sure it is.
Also makes sure we handle space urls without a trailing slash, since I think no trailing slash is consistent with how we configure them elsewhere and I'm not sure which one Nexl is using.
=> Use spaceUrl for existing spaces
