FlatFilers/flatfile-core-libraries

.changeset/yellow-starfishes-walk.md, packages/cli/src/shared/constants.ts
- Resolves https://github.com/FlatFilers/support-triage/issues/981
- Syncs the Flatfile CLI deploy topics with the Flatfile API topics as defined here - https://github.com/FlatFilers/Platform/blob/main/apps/platform/src/events/topics.ts
=> Syncs Deploy Topics

.changeset/curvy-papayas-visit.md, apps/vanilla/package.json, package-lock.json, packages/angular/package.json, packages/javascript/FlatfileJavascript.ts, packages/javascript/package.json, packages/react/package.json, packages/react/src/hooks/usePortal.tsx, packages/v2-shims/package.json, packages/v2-shims/src/plugins/validators.ts, packages/vue/package.json, packages/vue/src/utils/createSimpleListener.ts
- feat: update types with updates from the new record-hook plugin;
- chore: changeset
=> feat: update deps of record-hook

.changeset/rare-grapes-double.md, package-lock.json, packages/cli/package.json, packages/cli/src/shared/constants.ts, packages/cli/src/shared/get-auth.ts, packages/cli/src/shared/messages.ts, packages/cli/src/shared/utils/polling.ts, packages/cli/src/x/actions/auth.action.ts, packages/cli/src/x/actions/deploy.action.ts, packages/cli/src/x/actions/develop.action.ts, packages/cli/src/x/actions/publish.action.ts, packages/cli/src/x/actions/publish.pubsub.ts, packages/cli/src/x/actions/quickstart.action.ts
This updates the `@flatfile/api` in the CLI to ^1.7.1. 
It also cleans up some noisy `@vercell/ncc` logging
=> feat: first pass at upgrading `@flatfile/api` in cli

.github/workflows/lint.yml, .github/workflows/test.yml
=> feat: only run Test and Lint action on PRs releasing new versions

.github/pull_request_template.md
=> feat: update changelog headline

.changeset/wicked-months-fly.md, packages/react/src/components/InitSpace.tsx
- feat: always remove iFrame when closing the confirm modal
- chore: changeset
=> feat: always close the iframe when closing the confirmation modal in `@flatfile/react`

.changeset/neat-buttons-invite.md, packages/vue/src/utils/createSimpleListener.ts
- fix: default api export bug
- chore: changeset
=> fix: Bug with @flatfile/api default export

.changeset/swift-carrots-invent.md, apps/getting-started/package.json, package-lock.json, packages/angular/package.json, packages/embedded-utils/src/types/index.ts, packages/listener-driver-pubsub/package.json
- Cleans up a dependency that was listed twice. 
- Fixes `package-lock.json` bug where a specific package wasn't installed.
=> fix: `@flatfile/embedded-utils` update

.changeset/metal-drinks-kiss.md, apps/vanilla/cdn.html, apps/vanilla/config.js, apps/vanilla/index.html, apps/vanilla/main.js, apps/vanilla/package.json, package-lock.json, packages/embedded-utils/package.json, packages/embedded-utils/src/types/IDefaultPageType.ts, packages/embedded-utils/src/types/Space.ts, packages/embedded-utils/src/types/index.ts, packages/embedded-utils/src/utils/findDefaultPage.ts, packages/embedded-utils/src/utils/index.ts, packages/embedded-utils/src/utils/updateDefaultPageInSpace.ts, packages/javascript/FlatfileJavascript.ts, packages/javascript/src/createIframe.ts, packages/react/src/components/FlatfileProvider.tsx, packages/react/src/hooks/useFlatfile.ts
- Introduced functionality to set the default page when preloading the Portal embed in the `@flatfile/javascript` package enhancing user experience and flexibility.
- Added better typing and organization across various components and utilities to improve code maintainability and developer experience.
```ts
window.initializeFlatfile = async (publishableKey) => {
const flatfileOptions = {
publishableKey,
workbook: config,
document: {
title: 'my title',
body: 'my body',
defaultPage: true
},
}
const space = await initializeFlatfile(flatfileOptions)
}
```
- **Vanilla App Configurations**: Enhanced the configuration setup in `apps/vanilla/config.js` to allow additional fields and updated naming conventions for better consistency.
- **CDN HTML and Main.js**: Adjustments in `cdn.html` and …
=> feat: add setting default page to `@flatfile/javascript` and shared logic to `@flatfile/embedded-utils`

.changeset/tough-beds-promise.md, package-lock.json, packages/react/src/components/CloseButton.tsx, packages/react/src/components/ConfirmCloseModal.tsx, packages/react/src/components/Document.tsx, packages/react/src/components/EmbeddedIFrameWrapper.tsx, packages/react/src/components/FlatfileContext.tsx, packages/react/src/components/FlatfileProvider.tsx, packages/react/src/components/Sheet.tsx, packages/react/src/components/Workbook.tsx, packages/react/src/components/legacy/InitSpace.tsx, packages/react/src/components/legacy/LegacySpace.tsx, packages/react/src/hooks/useEvent.ts, packages/react/src/hooks/useFlatfile.ts, packages/react/src/hooks/usePlugin.ts, packages/react/src/types/IClosePortal.ts, packages/react/src/types/ICreateSpaceInternal.ts, packages/react/src/types/index.ts, packages/react/src/utils/createSpaceInternal.ts
- Enhanced typing and organization for better developer experience.
- **CloseButton**: Refactored to a more concise functional component format.
- **ConfirmCloseModal**: Exported directly for better modularity and reusability.
- Refactoring for improved readability and maintainability.
- Introduced `DefaultPageConfig` for structured default page settings.
- Conditional logic optimization in `usePlugin` and `useEvent` hooks.
- Enhanced record hook handling with conditional slug determination.
- Streamlined event handling for submissions with conditional settings application.
- Updated `useEvent` hook to prevent unnecessary event registrations if no callback is provided.
- Improved space initialization checks and modal component consistency.
These updates aim to improve usability and …
=> chore: `@flatfile/react` cleanup

.changeset/thick-items-decide.md, package-lock.json, packages/listener-driver-pubsub/package.json
=> feat: Update Pubsub Driver

.changeset/gentle-dancers-prove.md, packages/cli/src/x/files/agent.js
- Replaces deprecated upload:completed event with the newer file:created event; The event bodies are the exact same, so no other changes should be needed
- No user facing change; Should be completely transparent
=> feat: Replace Deprecated upload:completed Event

package-lock.json, package.json
NA
Run an npm install without any creds.
=> Make changelog dep optional

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
NA
If the test and lint steps on this PR pass, that should be evidence this will be fine.
=> Remove npm auth on actions other than changelog

.github/workflows/cl-create.yml, package-lock.json, package.json
NA
We'll have to cut a release but I did test it in another test package & it worked.
=> Trigger on release published

.changeset/metal-weeks-bow.md
Version bump for `@flatfile/javascript` to 1.3.11
Internationalization support
=> feat(javascript): add i18n to wrapper

.changeset/angry-doors-flow.md, apps/getting-started/package.json, package-lock.json, packages/cli/package.json, packages/cli/src/x/actions/deploy.action.ts
=> feat: Sends the source map file for the agent code to Flatfile

.github/workflows/release.yml
=> Use built in token

cl-config.yml
=> Fix javascript package entry in cl config

.github/workflows/cl-create.yml, .github/workflows/release.yml
Updates github actions to use github app auth.
NA
I believe we'll have to merge and release an update to test.
=> Use github app auth

.github/scripts/getReviewer.js
Fixing script, set env vars and run to see if it works (you may need to add a log).
=> Update script for use outside module

.github/scripts/getReviewers.js, .github/workflows/cl-create.yml
=> Fix output and invoke command

.changeset/tall-dolphins-laugh.md, .gitignore, apps/react/app/package.json, apps/react/app/reuse-space-example/ReusableSpaceExample.tsx, apps/react/app/reuse-space-example/index.tsx, package.json, packages/react/src/components/Workbook.tsx, packages/react/src/components/_tests_/Workbook.spec.tsx
- feat: fix multiple Workbook onSubmit bug
- chore: changeset and .gitignore
=> fix: Update Workbook onSubmit Issues

.github/scripts/getReviewers.js
Fixes reviewer format for gh cli
=> Join reviewers

.changeset/five-penguins-fold.md, package-lock.json, packages/listener/src/events/flatfile.event.ts
This PR introduces User Secrets, enabling users to pass an actorId to retrieve secrets via the ADK. A new actor_id parameter has been added, which distinguishes user-level secrets from space or environment-level secrets.
- make a call to the secrets SDK that includes an actorId param.
=> DAT-164:  User Secrets SDK Updates

.changeset/small-scissors-argue.md, packages/javascript/package.json, packages/javascript/rollup.config.js, packages/javascript/tsup.config.mjs, packages/react/package.json, packages/react/rollup.config.js, packages/react/tsup.config.mjs
Closes https://github.com/FlatFilers/support-triage/issues/1642
=> feat: browser-only builds

.changeset/chilly-pans-build.md, packages/javascript/rollup.config.js
This PR fixes the Javascript SDK's UMD build by removing the externals
Closes https://github.com/FlatFilers/support-triage/issues/1642
=> Fix Javascript SDK's UMD build

.changeset/nine-files-tickle.md, apps/react/app/config.ts, apps/react/app/examples/externalapi.tsx, apps/react/app/examples/joinFields.tsx, apps/react/app/examples/npmExample.tsx, apps/react/app/examples/splitFields.tsx, apps/react/app/examples/submitExample.tsx, packages/javascript/src/services/workbook.ts, packages/react/src/utils/constants.ts
Closes https://github.com/FlatFilers/support-triage/issues/1673
=> Add "Submit" button translation

.changeset/silent-toes-bow.md, packages/embedded-utils/src/utils/createListener.ts, packages/javascript/src/listener.ts, packages/react/src/hooks/legacy/usePortal.tsx, packages/react/src/utils/constants.ts, packages/vue/src/utils/createSimpleListener.ts
Closes https://github.com/FlatFilers/support-triage/issues/1675
=> feat: translate "Starting job" message

.changeset/slow-bats-poke.md, package-lock.json, packages/cli/package.json
Update rollup dependency from 2.79.1 -> 2.79.2
=> Update rollup 2.79.1 -> 2.79.2

.changeset/popular-cycles-wonder.md, packages/cli/src/x/helpers/agent.table.ts
Fixes last updated date time format to resolve invalid date bug
=> Fix date format listing agents

.changeset/angry-squids-cry.md
=> Add changeset

apps/sandbox/package.json, package-lock.json, packages/configure/package.json, packages/embedded-utils/package.json, packages/expression-lang/package.json, packages/hooks/package.json, packages/orm/package.json
Implementing dev reports that Dependabot is trying to scan archived private repo; this should fix that.
=> Replace any archived repo refs

.changeset/heavy-bugs-deny.md, packages/cli/src/index.ts, packages/cli/src/x/actions/deploy.action.ts
- Adds a ci option to the deploy command that will disable any prompting
=> feat: Adds CI Option To Deploy Command

.changeset/pretty-cows-love.md
=> @flatfile/react@7.13.8

.changeset/ninety-insects-provide.md, packages/javascript/src/createIframe.ts, packages/javascript/src/startFlatfile.ts, packages/react/src/components/EmbeddedIFrameWrapper.tsx, packages/react/src/components/FlatfileContext.tsx, packages/react/src/components/FlatfileProvider.tsx, packages/react/src/components/_tests_/FlatfileProvider.spec.tsx
=> Send param to not replay events when reusing space

.changeset/nasty-hounds-wave.md, apps/vanilla/package.json, package-lock.json, packages/cli/package.json, packages/cli/src/config.ts, packages/cli/src/index.ts, packages/cli/src/shared/get-auth.ts, packages/cli/src/x/actions/delete.action.ts, packages/cli/src/x/actions/deploy.action.ts, packages/cli/src/x/actions/develop.action.ts, packages/cli/src/x/actions/download.action.ts
This PR adds the ability to namespace an agent
=> deploy namespaced agents
